### ISSUE TITLE
raise JSONDecodeError

### ISSUE THREAD

**Issue by VionaWang** [ssut/py-googletrans#83]
Hi, my code is just simply as follows:

import googletrans
from googletrans import Translator
translator = Translator()
translator.translate('bonjour')

I would like to test the package and the text is so short within the limit. But it raise error:
raise JSONDecodeError("Expecting value", s, err.value) from None

and the error message is
JSONDecodeError: Expecting value

Can anybody help me? It is really urgent and I don't know how to deal with it since the text is so short.
Thanks a lot!

**Comment by VionaWang** [comment]
@ssut

**Comment by VionaWang** [comment]
@josemoralesp @Paethon @vuolter @universeroc

**Comment by stephwag** [comment]
@VionaWang Check out #77, the lib pretty much won't work until #78 is merged. You'll have to make a fork and apply the PR there. (could also borrow mine since it is same thing) https://github.com/stephwag/py-googletrans

**Comment by raj-adroit** [comment]
Error trace:
```sh
/root/py-googletrans/googletrans/client.pyc in translate(self, text, dest, src)
    170 
    171         origin = text
--> 172         data = self._translate(text, dest, src)
    173 
    174         # this code will be updated when the format is changed.

/root/py-googletrans/googletrans/client.pyc in _translate(self, text, dest, src)
     79         r = self.session.get(url, params=params)
     80 
---> 81         data = utils.format_json(r.text)
     82         return data
     83 

/root/py-googletrans/googletrans/utils.pyc in format_json(original)
     60         converted = json.loads(original)
     61     except ValueError:
---> 62         converted = legacy_format_json(original)
     63 
     64     return converted

/root/py-googletrans/googletrans/utils.pyc in legacy_format_json(original)
     52             text = text[:p] + states[j][1] + text[nxt:]
     53 
---> 54     converted = json.loads(text)
     55     return converted
     56 

/usr/lib/python2.7/json/__init__.pyc in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    337             parse_int is None and parse_float is None and
    338             parse_constant is None and object_pairs_hook is None and not kw):
--> 339         return _default_decoder.decode(s)
    340     if cls is None:
    341         cls = JSONDecoder

/usr/lib/python2.7/json/decoder.pyc in decode(self, s, _w)
    362 
    363         """
--> 364         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    365         end = _w(s, end).end()
    366         if end != len(s):

/usr/lib/python2.7/json/decoder.pyc in raw_decode(self, s, idx)
    380             obj, end = self.scan_once(s, idx)
    381         except StopIteration:
--> 382             raise ValueError("No JSON object could be decoded")
    383         return obj, end

ValueError: No JSON object could be decoded
```

**Comment by rayastar** [comment]
same error, but yesterday it was worked

**Comment by Paethon** [comment]
I just switched to `googletrans`
Does the same (but just for the google translator) and works

**Comment by dripti** [comment]
same error, any fix on this?

**Comment by VionaWang** [comment]
@stephwag , Hi , Thanks for your advise. But I have hanged and it is the issue that happens after the change. I have tried and found that if I am using WiFi for a long time and it does not work, when I change to other network like ethernet it works again, vice versa. It is strange. Could you help me?

**Comment by VionaWang** [comment]
Hey there, have you tried change your network? I don't know why it works for a while but if you change your network it works again. That's the way I fixed it.

**Comment by dripti** [comment]
it worked for 10 queries, after that it started giving json error

**Comment by dripti** [comment]
@stephwag is there any fix for json decode error yet?

**Comment by Paethon** [comment]
What I do is to give alternative addresses to use for querying. The system then uses all of them and you don't get blocked as quickly. 

```python
translate_urls = ["translate.google.com", "translate.google.co.kr",
                      "translate.google.at", "translate.google.de",
                      "translate.google.ru", "translate.google.ch",
                      "translate.google.fr", "translate.google.es"]
tr = Translator(service_urls=translate_urls)
```

**Comment by markolofsen** [comment]
Fixed library are here [https://pypi.org/project/py-translator/](https://pypi.org/project/py-translator/)

**Comment by alabrashJr** [comment]
@markolofsen no it's not, I still get the same error

**Comment by khaerulumam42** [comment]
Still get error, try print `text` on googletrans API on they say my computer detected as bot
